{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.4.0-alpha01.aar",
          "url": "fragment-1.4.0-alpha01.aar",
          "size": 306658,
          "sha512": "beeda35298299181a166c13b0fcea48f8ceba10f8917bea31a9ada6e3605dfcfb77a8ad477da5bb4fd7759540c7463311d4d31abe331e6fbc107b1efadf51bd4",
          "sha256": "54fda741911de5c6b8ecc5bd9471acb07af7c2d4f10b7af500319222ac9759db",
          "sha1": "050f20946f928b7c08e691fe5cedabd3bd8a6518",
          "md5": "b9f0c50ffacaeaddee641db95af31b5c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.viewpager",
          "module": "viewpager",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.loader",
          "module": "loader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-1.4.0-alpha01.aar",
          "url": "fragment-1.4.0-alpha01.aar",
          "size": 306658,
          "sha512": "beeda35298299181a166c13b0fcea48f8ceba10f8917bea31a9ada6e3605dfcfb77a8ad477da5bb4fd7759540c7463311d4d31abe331e6fbc107b1efadf51bd4",
          "sha256": "54fda741911de5c6b8ecc5bd9471acb07af7c2d4f10b7af500319222ac9759db",
          "sha1": "050f20946f928b7c08e691fe5cedabd3bd8a6518",
          "md5": "b9f0c50ffacaeaddee641db95af31b5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-1.4.0-alpha01-sources.jar",
          "url": "fragment-1.4.0-alpha01-sources.jar",
          "size": 190010,
          "sha512": "a3e24ad2ae32f8043a24a3af9a8ee5e1c0a1a504142779973d97bef7a0ba4c454f2f10b3c4e9dfc2f8e38d2ee9dfa3255e39339a1a4d708c3b89b02ee7d1e6ec",
          "sha256": "8470228ce22fb2069eaa435e1dea8677547120cd2fad8216b93e6816691af281",
          "sha1": "00f5db12c5e7b57366d52733f263f7a504f7af8b",
          "md5": "655ddefcbaf44d88041c0c094600ff17"
        }
      ]
    }
  ]
}
