{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.4.0-alpha01.aar",
          "url": "fragment-testing-1.4.0-alpha01.aar",
          "size": 42005,
          "sha512": "ba917b9f617727f4449f9da26315b0e4c5a7d581bfcdb51f9e2570271e0dc12e438752a58c8aef850f9486efff2e9205c3c376003348881f51dc40a5517f5d99",
          "sha256": "9b05541e8e9ec0fb97db5880dd98c835699ed9b9bc3059cea36c4e5dedfc882a",
          "sha1": "4e625378cf75d9c99fcc40928b479ae6e43f6ff5",
          "md5": "75245100f6535ae2f121120e08f06fc0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.4.0-alpha01.aar",
          "url": "fragment-testing-1.4.0-alpha01.aar",
          "size": 42005,
          "sha512": "ba917b9f617727f4449f9da26315b0e4c5a7d581bfcdb51f9e2570271e0dc12e438752a58c8aef850f9486efff2e9205c3c376003348881f51dc40a5517f5d99",
          "sha256": "9b05541e8e9ec0fb97db5880dd98c835699ed9b9bc3059cea36c4e5dedfc882a",
          "sha1": "4e625378cf75d9c99fcc40928b479ae6e43f6ff5",
          "md5": "75245100f6535ae2f121120e08f06fc0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-testing-1.4.0-alpha01-sources.jar",
          "url": "fragment-testing-1.4.0-alpha01-sources.jar",
          "size": 5230,
          "sha512": "f1e0443a3ca2ddaae97aa7e873dd408a5ca032f97166caa2aec6a4a442b1ea36ab9f47f3d9faa770a7f28b3a1a95ede9789ac4c7d42e1cee32ca51079c006e02",
          "sha256": "bdb4b29f8198f1a4f3aa1c3ef3ecbf930fce16ea03d60d1d06a0a93e7f319c21",
          "sha1": "18a0d9ed15234fa214b6f5e4cba1977276665f26",
          "md5": "f11d5a1090ec4833de13821ccffa3233"
        }
      ]
    }
  ]
}
